"""live_sim a evolution simulation
Copyright (C) 2019  Leo Basov

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
long with this program. If not, see <https://www.gnu.org/licenses/>."""

import sys
import random

sys.path.append('../../neat-python/.')

from neat.network import Node
from neat.network import Gene
from neat.network import Network

class Brain(Network):
	"""This is the brain of of the new creature typ

	The creature is provided with a set of sensory input as well as outputs generated by the network.
	The set of input and output values is fixed while the rest of the network can evolve freely.

	"""
	def __init__(self):
		"""
		"""
		super().__init__()

		self._add_input_node(1)
		self._add_input_node(2)

		self._add_output_node(3)

		self.__set_up_genes()

	def __set_up_genes(self):
		gene1 = Gene(in_node = 0, out_node = 3, weight = 10 - 20.0*random.random(), enabled = True)
		gene2 = Gene(in_node = 1, out_node = 3, weight = 10 - 20.0*random.random(), enabled = True)
		gene3 = Gene(in_node = 2, out_node = 3, weight = 10 - 20.0*random.random(), enabled = True)

		self.set_genes([gene1, gene2, gene3])

class Mutator:
	pass

class SmartCreature:
	pass